### ISSUE TITLE
Custom values on Task objects

### ISSUE THREAD

**Issue by DannyJoris** [pa11y/webservice#34]
Is there a way to add new keys and values to Task objects? I manually added Task objects with some extra values to categorize them, but the webservice didn't include these values when retrieving the objects.

**Comment by DannyJoris** [comment]
Oh, is that what the annotations are for? https://github.com/pa11y/webservice/wiki/Resource-Types#task

**Comment by rowanmanning** [comment]
Hi Danny, that's because all of the tasks are run through [this function](https://github.com/pa11y/webservice/blob/master/model/task.js#L198) before being output, to sanitize the data and resolve slight differences where we've introduced new features. This use-case seems quite specific, you could fork the webservice and add your fields in to the function above so that they appear in the output?
