### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by DannyJoris** [pa11y/webservice#35]
It would be handy if the webservice would be able to accommodate pagination. Either with prev/next functionality or splitting the tasks up alphabetically.

**Comment by rowanmanning** [comment]
Hi Danny. As we're ramping down feature development for the webservice this is unlikely to get added. Due to the likely complexity of the change, I'm not sure whether we could commit to reviewing a PR and maintaining it either. As mentioned in #36, we could look at adding this into [Sidekick](https://github.com/pa11y/sidekick).
